[package]
name = "json-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { workspace = true }
lib = { path = "../lib", package = "json-lib" }
log = "0.4.25"
sha2-v0-10-8 = { workspace = true }
rsa = { workspace = true }